import type { Question, Topic } from './types'
export const TOPICS: Record<'vocab' | 'grammar', Topic> = {
	vocab: {
		id: 1,
		slug: 'vocab',
		nameEn: 'Vocabulary',
		nameJa: '語彙',
		minLevel: 'N4',
		sortOrder: 1,
	},
	grammar: {
		id: 2,
		slug: 'grammar',
		nameEn: 'Grammar',
		nameJa: '文法',
		minLevel: 'N4',
		sortOrder: 2,
	},
}

let choiceId = 0

/** Builds one question; the FIRST body given is the correct one. */
function q(
	id: number,
	level: Question['level'],
	topic: Topic,
	prompt: string,
	bodies: readonly string[],
	explanation: string,
): Question {
	return {
		id,
		level,
		topic,
		format: 'multiple_choice',
		prompt,
		promptFurigana: null,
		promptEn: null,
		audioUrl: null,
		explanation,
		difficulty: 1,
		choices: bodies.map((body, i) => ({
			id: ++choiceId,
			body,
			isCorrect: i === 0,
			position: i,
		})),
	}
}

export const OFFICIAL_QUESTIONS: readonly Question[] = [
	// ── JLPT N4 Questions (1–10) ──────────────────────────────────────────────
	q(
		1,
		'N4',
		TOPICS.vocab,
		'都合 (つごう) means "convenience / schedule circumstances".',
		['True', 'False'],
		"True: 都合 (つごう) refers to one's availability, convenience, or circumstances.",
	),
	q(
		2,
		'N4',
		TOPICS.vocab,
		'案内 (あんない) means "safety / peace of mind".',
		['False', 'True'],
		'False: 案内 (あんない) means "to guide / show around". "Safety / peace of mind" is 安心 (あんしん) or 安全 (あんぜん).',
	),
	q(
		3,
		'N4',
		TOPICS.vocab,
		'経験 (けいけん) means "experience".',
		['True', 'False'],
		'True: 経験 (けいけん) means "experience".',
	),
	q(
		4,
		'N4',
		TOPICS.vocab,
		'特別',
		['とくべつ', 'とっべつ', 'とうべつ', 'とくへつ'],
		'A (とくべつ): Watch out for double consonants; it is full とく, not とっ.',
	),
	q(
		5,
		'N4',
		TOPICS.vocab,
		'急行',
		['きゅうこう', 'きゅこう', 'きょうこう', 'きゅうぎょう'],
		'A (きゅうこう): Both kanji take long vowels (きゅう + こう).',
	),
	q(
		6,
		'N4',
		TOPICS.vocab,
		'準備',
		['じゅんび', 'じゅうび', 'じゅんぴ', 'じんび'],
		'A (じゅんび): Short じゅん + voiced び (not ぴ or ひ).',
	),
	q(
		7,
		'N4',
		TOPICS.vocab,
		'注意',
		['ちゅうい', 'しゅうい', 'ちゅい', 'じゅうい'],
		'A (ちゅうい): 注 is ちゅう with a long う, not しゅう.',
	),
	q(
		8,
		'N4',
		TOPICS.vocab,
		'空港',
		['くうこう', 'くこう', 'こうこう', 'くうごう'],
		'A (くうこう): 空 here is read as くう, while 港 is こう (unvoiced).',
	),
	q(
		9,
		'N4',
		TOPICS.vocab,
		'約束',
		['やくそく', 'やくぞく', 'やっそく', 'やくしょく'],
		'A (やくそく): 束 is unvoiced (そく), not voiced (ぞく).',
	),
	q(
		10,
		'N4',
		TOPICS.vocab,
		'自転車',
		['じてんしゃ', 'じでんしゃ', 'じとうしゃ', 'ちてんしゃ'],
		'A (じてんしゃ): 自 (じ) + 転 (てん, unvoiced) + 車 (しゃ).',
	),

	// ── JLPT N3 Questions (11–20) ──────────────────────────────────────────────
	q(
		11,
		'N3',
		TOPICS.vocab,
		'複雑 (ふくざつ) means "simple / uncomplicated".',
		['False', 'True'],
		'False: 複雑 (ふくざつ) means "complex / complicated". "Simple" is 単純 (たんじゅん) or 簡単 (かんたん).',
	),
	q(
		12,
		'N3',
		TOPICS.vocab,
		'賛成 (さんせい) means "approval / agreement".',
		['True', 'False'],
		'True: 賛成 (さんせい) means "agreement / approval" (opposite: 反対 はんたい).',
	),
	q(
		13,
		'N3',
		TOPICS.vocab,
		'冗談 (じょうだん) means "serious matter / emergency".',
		['False', 'True'],
		'False: 冗談 (じょうだん) means "joke / jest".',
	),
	q(
		14,
		'N3',
		TOPICS.vocab,
		'遠慮',
		['えんりょ', 'えんりょう', 'えいりょ', 'えんろ'],
		'A (えんりょ): Common trap: 慮 is a short vowel (りょ), not long (りょう).',
	),
	q(
		15,
		'N3',
		TOPICS.vocab,
		'技術',
		['ぎじゅつ', 'きじゅつ', 'ぎじつ', 'ぎしゅつ'],
		'A (ぎじゅつ): 技 is voiced (ぎ), and 術 is じゅつ (distinguish from 実 じつ).',
	),
	q(
		16,
		'N3',
		TOPICS.vocab,
		'直接',
		['ちょくせつ', 'ちょっせつ', 'じょくせつ', 'ちょくぜつ'],
		'A (ちょくせつ): Direct/directly. Kept as full く (not sokuon っ), and 接 is unvoiced (せつ).',
	),
	q(
		17,
		'N3',
		TOPICS.vocab,
		'詳細',
		['しょうさい', 'しょさい', 'そうさい', 'じょうさい'],
		'A (しょうさい): Details/detailed. 詳 uses the long sound しょう.',
	),
	q(
		18,
		'N3',
		TOPICS.vocab,
		'横断',
		['おうだん', 'おんだん', 'こうだん', 'おうたん'],
		"A (おうだん): Crossing/traversing. 横 has the on'yomi おう, and 断 is voiced (だん).",
	),
	q(
		19,
		'N3',
		TOPICS.vocab,
		'結局',
		['けっきょく', 'けつきょく', 'けっきょう', 'けいきょく'],
		'A (けっきょく): In the end/after all. Uses the sokuon けっ and short きょく.',
	),
	q(
		20,
		'N3',
		TOPICS.vocab,
		'判断',
		['はんだん', 'はんたん', 'ばんだん', 'はんだつ'],
		'A (はんだん): Judgment/decision. 判 is unvoiced (はん) while 断 is voiced (だん).',
	),
]
