import type { Question, Topic } from './types'
import { TOPICS } from './mock-data.ts'

export { TOPICS }

let choiceId = 0

/** Builds one question; the FIRST body given is the correct one. */
function q(
	id: number,
	level: Question['level'],
	topic: Topic,
	prompt: string,
	bodies: readonly string[],
	explanation: string,
): Question {
	return {
		id,
		level,
		topic,
		format: 'multiple_choice',
		prompt,
		promptFurigana: null,
		promptEn: null,
		audioUrl: null,
		explanation,
		difficulty: 1,
		choices: bodies.map((body, i) => ({
			id: ++choiceId,
			body,
			isCorrect: i === 0,
			position: i,
		})),
	}
}

export const OFFICIAL_QUESTIONS: readonly Question[] = [
	// ── JLPT N4 Questions (1–15) ──────────────────────────────────────────────
	q(
		1,
		'N4',
		TOPICS.grammar,
		'「雨が降るかもしれませんから、傘を持っていきます。」',
		['True', 'False'],
		'〜かもしれません (might) correctly follows dictionary form 降る.',
	),
	q(
		2,
		'N4',
		TOPICS.grammar,
		'「この料理はおいしいですが、高すぎません。」 (Intended: This food is delicious, but not too expensive.)',
		['False', 'True'],
		'〜すぎる does not naturally conjugate to 〜ません to express "not overly". Use それほど高くありません.',
	),
	q(
		3,
		'N4',
		TOPICS.grammar,
		'「図書館で大きな声で話してはいけません。」',
		['True', 'False'],
		'〜てはいけません is standard for prohibition ("must not").',
	),
	q(
		4,
		'N4',
		TOPICS.grammar,
		'「私は弟に宿題を手伝われました。」 (Intended: I helped my younger brother with his homework.)',
		['False', 'True'],
		'Passive 手伝われました awkwardly means "I was helped by brother". Natural: 弟の宿題を手伝ってあげました.',
	),
	q(
		5,
		'N4',
		TOPICS.grammar,
		'「日本へ行く前に、ひらがなを覚えておきました。」',
		['True', 'False'],
		'〜ておく denotes doing an action in advance before a specific event.',
	),
	q(
		6,
		'N4',
		TOPICS.grammar,
		'「明日は早く起きなければならないです。」',
		['True', 'False'],
		'〜なければならない expresses necessity ("must").',
	),
	q(
		7,
		'N4',
		TOPICS.grammar,
		'「この本はもう読んだことがあります。」',
		['False', 'True'],
		'もう (already) clashes with experiential 〜たことがある. Use もう読みました or 読んだことがあります.',
	),
	q(
		8,
		'N4',
		TOPICS.grammar,
		'毎朝、出かける前にニュースを＿＿＿ようにしています。',
		['見る', '見て', '見た', '見よう'],
		'辞書形 + ようにする indicates conscious effort to form a daily habit.',
	),
	q(
		9,
		'N4',
		TOPICS.grammar,
		'このケーキは甘＿＿＿て、とてもおいしいです。',
		['く', 'すぎ', 'そう', 'ない'],
		'The -te form connecting i-adjectives replaces -い with -くて (甘くて).',
	),
	q(
		10,
		'N4',
		TOPICS.grammar,
		'窓が＿＿＿ありますから、部屋が涼しいです。',
		['開けて', '開いて', '開いた', '開けたら'],
		'他動詞 (transitive) + てある denotes an intentional resulting state: 開けてあります.',
	),
	q(
		11,
		'N4',
		TOPICS.grammar,
		'友達の結婚式に出席する＿＿＿に、新しいスーツを買いました。',
		['ため', 'よう', 'から', 'ので'],
		'Noun/Verb + のために denotes direct purpose ("in order to attend").',
	),
	q(
		12,
		'N4',
		TOPICS.grammar,
		'「すみません、ペンを＿＿＿いただけませんか。」',
		['貸して', '借りて', '貸されて', '借りられて'],
		'Polite request for the listener to lend: 貸していただけませんか.',
	),
	q(
		13,
		'N4',
		TOPICS.grammar,
		'寒くなってきたので、風邪をひかない＿＿＿気をつけてください。',
		['ように', 'ために', 'そうに', 'みたいに'],
		'Negative purpose / caution pattern: ない形 + ように気をつける.',
	),
	q(
		14,
		'N4',
		TOPICS.grammar,
		'先生、この荷物をお持ち＿＿＿。',
		['します', 'なります', 'されます', 'くださいます'],
		'Humble form (Kenjougo) formula: お + verb stem + します (お持ちします).',
	),
	q(
		15,
		'N4',
		TOPICS.grammar,
		'母＿＿＿頼まれて、スーパーへ牛乳を買いに行きました。',
		['に', 'を', 'で', 'へ'],
		'The agent initiating the passive action/request is marked by に (母に頼まれて).',
	),

	// ── JLPT N3 Questions (16–30) ──────────────────────────────────────────────
	q(
		16,
		'N3',
		TOPICS.grammar,
		'「彼はどんなに忙しくても、毎日日本語の勉強を続けている。」',
		['True', 'False'],
		'どんなに〜ても correctly expresses "no matter how much / how...".',
	),
	q(
		17,
		'N3',
		TOPICS.grammar,
		'「せっかく料理を作ったのに、家族は誰も食べなかった。」',
		['True', 'False'],
		'せっかく〜のに expresses regret/disappointment despite special effort.',
	),
	q(
		18,
		'N3',
		TOPICS.grammar,
		'「この機械は古くなるにつれて、使いやすくなった。」',
		['False', 'True'],
		'〜につれて shows proportional natural progression; machines getting easier purely as they age is illogical.',
	),
	q(
		19,
		'N3',
		TOPICS.grammar,
		'「雨が止まない限り、サッカーの試合は始められない。」',
		['True', 'False'],
		'〜ない限り means "unless / as long as not" (unless rain stops, cannot start).',
	),
	q(
		20,
		'N3',
		TOPICS.grammar,
		'「試験の日は、鉛筆をはじめ消しゴムなどの文房具を持参すること。」',
		['True', 'False'],
		'Aをはじめ(として) introduces a representative example followed by similar items.',
	),
	q(
		21,
		'N3',
		TOPICS.grammar,
		'「彼女は病気にもかかわらず、学校を休んだ。」',
		['False', 'True'],
		'〜にもかかわらず expresses "despite / contrary to expectations". Resting when sick is expected, so it should be 休まなかった.',
	),
	q(
		22,
		'N3',
		TOPICS.grammar,
		'「明日の会議について、メールで連絡させていただきます。」',
		['True', 'False'],
		'〜について + humble させていただきます is standard respectful business Japanese.',
	),
	q(
		23,
		'N3',
		TOPICS.grammar,
		'渋滞の＿＿＿、飛行機の出発時間に遅れてしまった。',
		['せいで', 'おかげで', 'たとえ', '反面'],
		'〜せいで assigns blame to a negative cause/result. おかげで is for positive results.',
	),
	q(
		24,
		'N3',
		TOPICS.grammar,
		'説明書を読んだ＿＿＿、組み立て方がよく分かりませんでした。',
		['うえで', 'とおりに', 'ついでに', '最中に'],
		'Verb-た + うえで means "after having done [action] / upon reviewing".',
	),
	q(
		25,
		'N3',
		TOPICS.grammar,
		'どんな困難が＿＿＿、最後まで諦めないつもりだ。',
		['あろうと', 'あるなら', 'あっても', 'あるばかりに'],
		'どんな + Volitional + と (あろうと) forms the formal N3/N2 pattern "no matter what difficulties arise".',
	),
	q(
		26,
		'N3',
		TOPICS.grammar,
		'実際に使って＿＿＿でなければ、この便利さは分からないだろう。',
		['みてから', 'みたあと', 'みたうえ', 'みる前'],
		'〜てからでなければ ... ない is a set N3 pattern meaning "unless X is done first, Y cannot be".',
	),
	q(
		27,
		'N3',
		TOPICS.grammar,
		'このレストランは料理が美味しい＿＿＿、値段もそれほど高くない。',
		['うえに', '一方で', 'かわりに', 'からして'],
		'〜うえに means "not only... but also", compounding positive aspects.',
	),
	q(
		28,
		'N3',
		TOPICS.grammar,
		'社長におかれましては、ますますご清栄の＿＿＿お慶び申し上げます。',
		['ことと', 'ものと', 'わけと', 'ためと'],
		'ご清栄のこととお慶び申し上げます is standard epistolary/business honorific phrasing.',
	),
	q(
		29,
		'N3',
		TOPICS.grammar,
		'ダイエット中なので、甘いお菓子は＿＿＿にしている。',
		['食べないよう', '食べないこと', '食べないはず', '食べないわけ'],
		'Conscious habit rule pattern: ない形 + ようにしている.',
	),
	q(
		30,
		'N3',
		TOPICS.grammar,
		'締め切りが明日なので、今夜は寝る＿＿＿にはいかない。',
		['わけ', 'はず', 'もの', 'こと'],
		'〜わけにはいかない expresses moral/circumstantial impossibility ("cannot afford to sleep").',
	),
]
