-- GENERATED FILE — do not edit by hand.
-- Source: src/lib/game/mock-data.ts, via scripts/generate-seed.ts
--
-- PLACEHOLDER CONTENT. The Japanese is correct, but this set has not been
-- reviewed against an official JLPT syllabus and must not be presented to
-- learners as authoritative study material. See PRODUCT.md.
--
-- Re-runnable: content rows are replaced, play data is left alone.

DELETE FROM choices;
DELETE FROM questions;
DELETE FROM topics;

INSERT INTO topics (id, slug, name_en, name_ja, min_level, sort_order, is_active) VALUES (1, 'vocab', 'Vocabulary', '語彙', 'N5', 1, 1);
INSERT INTO topics (id, slug, name_en, name_ja, min_level, sort_order, is_active) VALUES (2, 'grammar', 'Grammar', '文法', 'N5', 2, 1);

INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (1, 'N4', 2, 'multiple_choice', '日本へ＿＿＿ことがあります。', NULL, NULL, NULL, '〜たことがある — to have done something before. "I have been to Japan."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (1, 1, '行った', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (2, 1, '行く', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (3, 1, '行って', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (4, 1, '行き', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (2, 'N4', 2, 'multiple_choice', '部屋を出る前に、電気を消さ＿＿＿。', NULL, NULL, NULL, '〜なければならない — must do. "You have to turn the light off before leaving."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (5, 2, 'なければなりません', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (6, 2, 'てもいいです', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (7, 2, 'たいです', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (8, 2, 'ましょうか', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (3, 'N4', 2, 'multiple_choice', '音楽を聞き＿＿＿勉強します。', NULL, NULL, NULL, '〜ながら — while doing. "I study while listening to music."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (9, 3, 'ながら', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (10, 3, 'ないで', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (11, 3, 'たり', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (12, 3, 'ので', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (4, 'N4', 2, 'multiple_choice', '明日雨が降っ＿＿＿、試合は中止です。', NULL, NULL, NULL, '〜たら — if / when. "If it rains tomorrow, the match is cancelled."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (13, 4, 'たら', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (14, 4, 'ても', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (15, 4, 'ながら', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (16, 4, 'のに', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (5, 'N4', 2, 'multiple_choice', 'この漢字の読み方を教えて＿＿＿ませんか。', NULL, NULL, NULL, '〜てくれませんか — asking a favour. "Could you teach me how to read this kanji?"', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (17, 5, 'くれ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (18, 5, 'あげ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (19, 5, 'いき', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (20, 5, 'おき', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (6, 'N4', 2, 'multiple_choice', '弟はまだ子ども＿＿＿、よく手伝ってくれます。', NULL, NULL, NULL, '〜のに — although. "Even though my brother is still a child, he helps a lot."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (21, 6, 'なのに', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (22, 6, 'だから', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (23, 6, 'なので', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (24, 6, 'だと', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (7, 'N4', 1, 'multiple_choice', '「やくそく」を漢字で書くと？', NULL, NULL, NULL, '約束（やくそく）— a promise, an appointment.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (25, 7, '約束', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (26, 7, '予約', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (27, 7, '契約', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (28, 7, '結束', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (8, 'N4', 1, 'multiple_choice', '分からないことを先生に＿＿＿しました。', NULL, NULL, NULL, '相談する — to consult, to talk something over. "I consulted my teacher."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (29, 8, '相談', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (30, 8, '招待', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (31, 8, '紹介', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (32, 8, '選択', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (9, 'N4', 1, 'multiple_choice', '旅行の＿＿＿をしています。', NULL, NULL, NULL, '準備（じゅんび）— preparation. "I am getting ready for the trip."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (33, 9, '準備', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (34, 9, '進歩', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (35, 9, '生産', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (36, 9, '事務', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (10, 'N4', 1, 'multiple_choice', 'この機械の使い方を＿＿＿してください。', NULL, NULL, NULL, '説明する — to explain. "Please explain how to use this machine."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (37, 10, '説明', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (38, 10, '説得', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (39, 10, '報告', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (40, 10, '注文', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (11, 'N4', 1, 'multiple_choice', '「くらべる」の意味に近いのはどれ？', NULL, NULL, NULL, '比べる＝比較する — to compare.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (41, 11, '比較する', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (42, 11, '想像する', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (43, 11, '解決する', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (44, 11, '応援する', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (12, 'N4', 1, 'multiple_choice', '駅までの道が＿＿＿分かりません。', NULL, NULL, NULL, '全然〜ない — not at all. "I have no idea how to get to the station."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (45, 12, 'ぜんぜん', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (46, 12, 'とても', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (47, 12, 'ずいぶん', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (48, 12, 'なるべく', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (13, 'N3', 2, 'multiple_choice', '彼が犯人に＿＿＿ありません。', NULL, NULL, NULL, '〜に違いない — must be, no doubt. "He must be the culprit."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (49, 13, '違い', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (50, 13, 'すぎ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (51, 13, 'かぎり', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (52, 13, 'ばかり', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (14, 'N3', 2, 'multiple_choice', '寝坊した＿＿＿、電車に乗り遅れた。', NULL, NULL, NULL, '〜せいで — because of (blame). "I missed the train because I overslept."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (53, 14, 'せいで', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (54, 14, 'おかげで', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (55, 14, 'ために', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (56, 14, 'ように', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (15, 'N3', 2, 'multiple_choice', '知っている＿＿＿、教えてくれなかった。', NULL, NULL, NULL, '〜くせに — despite, and yet (with reproach). "He knew, and still didn''t tell me."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (57, 15, 'くせに', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (58, 15, 'ながら', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (59, 15, 'ばかりに', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (60, 15, 'うえに', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (16, 'N3', 2, 'multiple_choice', '彼女に会う＿＿＿、元気をもらう。', NULL, NULL, NULL, '〜たびに — every time. "Every time I see her, she cheers me up."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (61, 16, 'たびに', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (62, 16, 'うちに', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (63, 16, 'ところに', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (64, 16, 'とたんに', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (17, 'N3', 2, 'multiple_choice', '嫌いな＿＿＿が、あまり食べません。', NULL, NULL, NULL, '〜わけではない — it is not that. "It''s not that I dislike it, I just don''t eat much."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (65, 17, 'わけではない', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (66, 17, 'ことはない', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (67, 17, 'はずがない', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (68, 17, 'ものではない', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (18, 'N3', 2, 'multiple_choice', '会議は来週の月曜日＿＿＿行われます。', NULL, NULL, NULL, '〜において — at / in (formal setting). "The meeting will be held on Monday."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (69, 18, 'において', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (70, 18, 'にとって', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (71, 18, 'によって', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (72, 18, 'について', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (19, 'N3', 1, 'multiple_choice', '痛くても＿＿＿してください。', NULL, NULL, NULL, '我慢（がまん）する — to endure, to put up with.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (73, 19, '我慢', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (74, 19, '遠慮', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (75, 19, '油断', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (76, 19, '無理', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (20, 'N3', 1, 'multiple_choice', '手続きが＿＿＿で、時間がかかった。', NULL, NULL, NULL, '面倒（めんどう）— troublesome, a hassle.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (77, 20, '面倒', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (78, 20, '慎重', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (79, 20, '快適', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (80, 20, '順調', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (21, 'N3', 1, 'multiple_choice', '「あいまい」の意味は？', NULL, NULL, NULL, '曖昧（あいまい）— vague, ambiguous.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (81, 21, 'はっきりしない', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (82, 21, 'とても正しい', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (83, 21, 'すぐ終わる', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (84, 21, 'よく知られた', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (22, 'N3', 1, 'multiple_choice', '仕事を先輩に＿＿＿しました。', NULL, NULL, NULL, '依頼（いらい）する — to request, to commission.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (85, 22, '依頼', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (86, 22, '依存', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (87, 22, '意識', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (88, 22, '維持', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (23, 'N3', 1, 'multiple_choice', '雨で試合が＿＿＿になった。', NULL, NULL, NULL, '中止（ちゅうし）— cancellation. "The match was called off."', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (89, 23, '中止', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (90, 23, '中断', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (91, 23, '中央', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (92, 23, '集中', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (24, 'N3', 1, 'multiple_choice', '彼の説明はとても＿＿＿だった。', NULL, NULL, NULL, '具体的（ぐたいてき）— concrete, specific.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (93, 24, '具体的', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (94, 24, '消極的', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (95, 24, '一時的', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (96, 24, '相対的', 0, 3);
