-- GENERATED FILE — do not edit by hand.
-- Source: src/lib/game/official-data.ts, via scripts/generate-seed.ts
--
-- Official JLPT N4 & N3 Question Set.
--
-- Re-runnable: content rows are replaced, play data is left alone.

DELETE FROM choices;
DELETE FROM questions;
DELETE FROM topics;

INSERT INTO topics (id, slug, name_en, name_ja, min_level, sort_order, is_active) VALUES (1, 'vocab', 'Vocabulary', '語彙', 'N4', 1, 1);
INSERT INTO topics (id, slug, name_en, name_ja, min_level, sort_order, is_active) VALUES (2, 'grammar', 'Grammar', '文法', 'N4', 2, 1);

INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (1, 'N4', 1, 'multiple_choice', '都合 (つごう) means "convenience / schedule circumstances".', NULL, NULL, NULL, 'True: 都合 (つごう) refers to one''s availability, convenience, or circumstances.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (1, 1, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (2, 1, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (2, 'N4', 1, 'multiple_choice', '案内 (あんない) means "safety / peace of mind".', NULL, NULL, NULL, 'False: 案内 (あんない) means "to guide / show around". "Safety / peace of mind" is 安心 (あんしん) or 安全 (あんぜん).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (3, 2, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (4, 2, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (3, 'N4', 1, 'multiple_choice', '経験 (けいけん) means "experience".', NULL, NULL, NULL, 'True: 経験 (けいけん) means "experience".', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (5, 3, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (6, 3, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (4, 'N4', 1, 'multiple_choice', '特別', NULL, NULL, NULL, 'A (とくべつ): Watch out for double consonants; it is full とく, not とっ.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (7, 4, 'とくべつ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (8, 4, 'とっべつ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (9, 4, 'とうべつ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (10, 4, 'とくへつ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (5, 'N4', 1, 'multiple_choice', '急行', NULL, NULL, NULL, 'A (きゅうこう): Both kanji take long vowels (きゅう + こう).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (11, 5, 'きゅうこう', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (12, 5, 'きゅこう', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (13, 5, 'きょうこう', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (14, 5, 'きゅうぎょう', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (6, 'N4', 1, 'multiple_choice', '準備', NULL, NULL, NULL, 'A (じゅんび): Short じゅん + voiced び (not ぴ or ひ).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (15, 6, 'じゅんび', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (16, 6, 'じゅうび', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (17, 6, 'じゅんぴ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (18, 6, 'じんび', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (7, 'N4', 1, 'multiple_choice', '注意', NULL, NULL, NULL, 'A (ちゅうい): 注 is ちゅう with a long う, not しゅう.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (19, 7, 'ちゅうい', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (20, 7, 'しゅうい', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (21, 7, 'ちゅい', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (22, 7, 'じゅうい', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (8, 'N4', 1, 'multiple_choice', '空港', NULL, NULL, NULL, 'A (くうこう): 空 here is read as くう, while 港 is こう (unvoiced).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (23, 8, 'くうこう', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (24, 8, 'くこう', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (25, 8, 'こうこう', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (26, 8, 'くうごう', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (9, 'N4', 1, 'multiple_choice', '約束', NULL, NULL, NULL, 'A (やくそく): 束 is unvoiced (そく), not voiced (ぞく).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (27, 9, 'やくそく', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (28, 9, 'やくぞく', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (29, 9, 'やっそく', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (30, 9, 'やくしょく', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (10, 'N4', 1, 'multiple_choice', '自転車', NULL, NULL, NULL, 'A (じてんしゃ): 自 (じ) + 転 (てん, unvoiced) + 車 (しゃ).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (31, 10, 'じてんしゃ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (32, 10, 'じでんしゃ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (33, 10, 'じとうしゃ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (34, 10, 'ちてんしゃ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (11, 'N3', 1, 'multiple_choice', '複雑 (ふくざつ) means "simple / uncomplicated".', NULL, NULL, NULL, 'False: 複雑 (ふくざつ) means "complex / complicated". "Simple" is 単純 (たんじゅん) or 簡単 (かんたん).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (35, 11, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (36, 11, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (12, 'N3', 1, 'multiple_choice', '賛成 (さんせい) means "approval / agreement".', NULL, NULL, NULL, 'True: 賛成 (さんせい) means "agreement / approval" (opposite: 反対 はんたい).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (37, 12, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (38, 12, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (13, 'N3', 1, 'multiple_choice', '冗談 (じょうだん) means "serious matter / emergency".', NULL, NULL, NULL, 'False: 冗談 (じょうだん) means "joke / jest".', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (39, 13, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (40, 13, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (14, 'N3', 1, 'multiple_choice', '遠慮', NULL, NULL, NULL, 'A (えんりょ): Common trap: 慮 is a short vowel (りょ), not long (りょう).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (41, 14, 'えんりょ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (42, 14, 'えんりょう', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (43, 14, 'えいりょ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (44, 14, 'えんろ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (15, 'N3', 1, 'multiple_choice', '技術', NULL, NULL, NULL, 'A (ぎじゅつ): 技 is voiced (ぎ), and 術 is じゅつ (distinguish from 実 じつ).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (45, 15, 'ぎじゅつ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (46, 15, 'きじゅつ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (47, 15, 'ぎじつ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (48, 15, 'ぎしゅつ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (16, 'N3', 1, 'multiple_choice', '直接', NULL, NULL, NULL, 'A (ちょくせつ): Direct/directly. Kept as full く (not sokuon っ), and 接 is unvoiced (せつ).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (49, 16, 'ちょくせつ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (50, 16, 'ちょっせつ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (51, 16, 'じょくせつ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (52, 16, 'ちょくぜつ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (17, 'N3', 1, 'multiple_choice', '詳細', NULL, NULL, NULL, 'A (しょうさい): Details/detailed. 詳 uses the long sound しょう.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (53, 17, 'しょうさい', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (54, 17, 'しょさい', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (55, 17, 'そうさい', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (56, 17, 'じょうさい', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (18, 'N3', 1, 'multiple_choice', '横断', NULL, NULL, NULL, 'A (おうだん): Crossing/traversing. 横 has the on''yomi おう, and 断 is voiced (だん).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (57, 18, 'おうだん', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (58, 18, 'おんだん', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (59, 18, 'こうだん', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (60, 18, 'おうたん', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (19, 'N3', 1, 'multiple_choice', '結局', NULL, NULL, NULL, 'A (けっきょく): In the end/after all. Uses the sokuon けっ and short きょく.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (61, 19, 'けっきょく', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (62, 19, 'けつきょく', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (63, 19, 'けっきょう', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (64, 19, 'けいきょく', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (20, 'N3', 1, 'multiple_choice', '判断', NULL, NULL, NULL, 'A (はんだん): Judgment/decision. 判 is unvoiced (はん) while 断 is voiced (だん).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (65, 20, 'はんだん', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (66, 20, 'はんたん', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (67, 20, 'ばんだん', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (68, 20, 'はんだつ', 0, 3);
