-- GENERATED FILE — do not edit by hand.
-- Source: src/lib/game/official-data.ts, via scripts/generate-seed.ts
--
-- Official JLPT N4 & N3 Question Set.
--
-- Re-runnable: content rows are replaced, play data is left alone.

DELETE FROM choices;
DELETE FROM questions;
DELETE FROM topics;

INSERT INTO topics (id, slug, name_en, name_ja, min_level, sort_order, is_active) VALUES (1, 'vocab', 'Vocabulary', '語彙', 'N4', 1, 1);
INSERT INTO topics (id, slug, name_en, name_ja, min_level, sort_order, is_active) VALUES (2, 'grammar', 'Grammar', '文法', 'N4', 2, 1);

INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (1, 'N4', 2, 'multiple_choice', '「雨が降るかもしれませんから、傘を持っていきます。」', NULL, NULL, NULL, '〜かもしれません (might) correctly follows dictionary form 降る.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (1, 1, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (2, 1, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (2, 'N4', 2, 'multiple_choice', '「この料理はおいしいですが、高すぎません。」 (Intended: This food is delicious, but not too expensive.)', NULL, NULL, NULL, '〜すぎる does not naturally conjugate to 〜ません to express "not overly". Use それほど高くありません.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (3, 2, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (4, 2, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (3, 'N4', 2, 'multiple_choice', '「図書館で大きな声で話してはいけません。」', NULL, NULL, NULL, '〜てはいけません is standard for prohibition ("must not").', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (5, 3, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (6, 3, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (4, 'N4', 2, 'multiple_choice', '「私は弟に宿題を手伝われました。」 (Intended: I helped my younger brother with his homework.)', NULL, NULL, NULL, 'Passive 手伝われました awkwardly means "I was helped by brother". Natural: 弟の宿題を手伝ってあげました.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (7, 4, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (8, 4, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (5, 'N4', 2, 'multiple_choice', '「日本へ行く前に、ひらがなを覚えておきました。」', NULL, NULL, NULL, '〜ておく denotes doing an action in advance before a specific event.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (9, 5, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (10, 5, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (6, 'N4', 2, 'multiple_choice', '「明日は早く起きなければならないです。」', NULL, NULL, NULL, '〜なければならない expresses necessity ("must").', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (11, 6, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (12, 6, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (7, 'N4', 2, 'multiple_choice', '「この本はもう読んだことがあります。」', NULL, NULL, NULL, 'もう (already) clashes with experiential 〜たことがある. Use もう読みました or 読んだことがあります.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (13, 7, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (14, 7, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (8, 'N4', 2, 'multiple_choice', '毎朝、出かける前にニュースを＿＿＿ようにしています。', NULL, NULL, NULL, '辞書形 + ようにする indicates conscious effort to form a daily habit.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (15, 8, '見る', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (16, 8, '見て', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (17, 8, '見た', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (18, 8, '見よう', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (9, 'N4', 2, 'multiple_choice', 'このケーキは甘＿＿＿て、とてもおいしいです。', NULL, NULL, NULL, 'The -te form connecting i-adjectives replaces -い with -くて (甘くて).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (19, 9, 'く', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (20, 9, 'すぎ', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (21, 9, 'そう', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (22, 9, 'ない', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (10, 'N4', 2, 'multiple_choice', '窓が＿＿＿ありますから、部屋が涼しいです。', NULL, NULL, NULL, '他動詞 (transitive) + てある denotes an intentional resulting state: 開けてあります.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (23, 10, '開けて', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (24, 10, '開いて', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (25, 10, '開いた', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (26, 10, '開けたら', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (11, 'N4', 2, 'multiple_choice', '友達の結婚式に出席する＿＿＿に、新しいスーツを買いました。', NULL, NULL, NULL, 'Noun/Verb + のために denotes direct purpose ("in order to attend").', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (27, 11, 'ため', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (28, 11, 'よう', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (29, 11, 'から', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (30, 11, 'ので', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (12, 'N4', 2, 'multiple_choice', '「すみません、ペンを＿＿＿いただけませんか。」', NULL, NULL, NULL, 'Polite request for the listener to lend: 貸していただけませんか.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (31, 12, '貸して', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (32, 12, '借りて', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (33, 12, '貸されて', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (34, 12, '借りられて', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (13, 'N4', 2, 'multiple_choice', '寒くなってきたので、風邪をひかない＿＿＿気をつけてください。', NULL, NULL, NULL, 'Negative purpose / caution pattern: ない形 + ように気をつける.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (35, 13, 'ように', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (36, 13, 'ために', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (37, 13, 'そうに', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (38, 13, 'みたいに', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (14, 'N4', 2, 'multiple_choice', '先生、この荷物をお持ち＿＿＿。', NULL, NULL, NULL, 'Humble form (Kenjougo) formula: お + verb stem + します (お持ちします).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (39, 14, 'します', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (40, 14, 'なります', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (41, 14, 'されます', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (42, 14, 'くださいます', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (15, 'N4', 2, 'multiple_choice', '母＿＿＿頼まれて、スーパーへ牛乳を買いに行きました。', NULL, NULL, NULL, 'The agent initiating the passive action/request is marked by に (母に頼まれて).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (43, 15, 'に', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (44, 15, 'を', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (45, 15, 'で', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (46, 15, 'へ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (16, 'N3', 2, 'multiple_choice', '「彼はどんなに忙しくても、毎日日本語の勉強を続けている。」', NULL, NULL, NULL, 'どんなに〜ても correctly expresses "no matter how much / how...".', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (47, 16, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (48, 16, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (17, 'N3', 2, 'multiple_choice', '「せっかく料理を作ったのに、家族は誰も食べなかった。」', NULL, NULL, NULL, 'せっかく〜のに expresses regret/disappointment despite special effort.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (49, 17, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (50, 17, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (18, 'N3', 2, 'multiple_choice', '「この機械は古くなるにつれて、使いやすくなった。」', NULL, NULL, NULL, '〜につれて shows proportional natural progression; machines getting easier purely as they age is illogical.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (51, 18, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (52, 18, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (19, 'N3', 2, 'multiple_choice', '「雨が止まない限り、サッカーの試合は始められない。」', NULL, NULL, NULL, '〜ない限り means "unless / as long as not" (unless rain stops, cannot start).', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (53, 19, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (54, 19, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (20, 'N3', 2, 'multiple_choice', '「試験の日は、鉛筆をはじめ消しゴムなどの文房具を持参すること。」', NULL, NULL, NULL, 'Aをはじめ(として) introduces a representative example followed by similar items.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (55, 20, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (56, 20, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (21, 'N3', 2, 'multiple_choice', '「彼女は病気にもかかわらず、学校を休んだ。」', NULL, NULL, NULL, '〜にもかかわらず expresses "despite / contrary to expectations". Resting when sick is expected, so it should be 休まなかった.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (57, 21, 'False', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (58, 21, 'True', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (22, 'N3', 2, 'multiple_choice', '「明日の会議について、メールで連絡させていただきます。」', NULL, NULL, NULL, '〜について + humble させていただきます is standard respectful business Japanese.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (59, 22, 'True', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (60, 22, 'False', 0, 1);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (23, 'N3', 2, 'multiple_choice', '渋滞の＿＿＿、飛行機の出発時間に遅れてしまった。', NULL, NULL, NULL, '〜せいで assigns blame to a negative cause/result. おかげで is for positive results.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (61, 23, 'せいで', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (62, 23, 'おかげで', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (63, 23, 'たとえ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (64, 23, '反面', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (24, 'N3', 2, 'multiple_choice', '説明書を読んだ＿＿＿、組み立て方がよく分かりませんでした。', NULL, NULL, NULL, 'Verb-た + うえで means "after having done [action] / upon reviewing".', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (65, 24, 'うえで', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (66, 24, 'とおりに', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (67, 24, 'ついでに', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (68, 24, '最中に', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (25, 'N3', 2, 'multiple_choice', 'どんな困難が＿＿＿、最後まで諦めないつもりだ。', NULL, NULL, NULL, 'どんな + Volitional + と (あろうと) forms the formal N3/N2 pattern "no matter what difficulties arise".', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (69, 25, 'あろうと', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (70, 25, 'あるなら', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (71, 25, 'あっても', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (72, 25, 'あるばかりに', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (26, 'N3', 2, 'multiple_choice', '実際に使って＿＿＿でなければ、この便利さは分からないだろう。', NULL, NULL, NULL, '〜てからでなければ ... ない is a set N3 pattern meaning "unless X is done first, Y cannot be".', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (73, 26, 'みてから', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (74, 26, 'みたあと', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (75, 26, 'みたうえ', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (76, 26, 'みる前', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (27, 'N3', 2, 'multiple_choice', 'このレストランは料理が美味しい＿＿＿、値段もそれほど高くない。', NULL, NULL, NULL, '〜うえに means "not only... but also", compounding positive aspects.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (77, 27, 'うえに', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (78, 27, '一方で', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (79, 27, 'かわりに', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (80, 27, 'からして', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (28, 'N3', 2, 'multiple_choice', '社長におかれましては、ますますご清栄の＿＿＿お慶び申し上げます。', NULL, NULL, NULL, 'ご清栄のこととお慶び申し上げます is standard epistolary/business honorific phrasing.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (81, 28, 'ことと', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (82, 28, 'ものと', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (83, 28, 'わけと', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (84, 28, 'ためと', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (29, 'N3', 2, 'multiple_choice', 'ダイエット中なので、甘いお菓子は＿＿＿にしている。', NULL, NULL, NULL, 'Conscious habit rule pattern: ない形 + ようにしている.', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (85, 29, '食べないよう', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (86, 29, '食べないこと', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (87, 29, '食べないはず', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (88, 29, '食べないわけ', 0, 3);
INSERT INTO questions (id, level, topic_id, format, prompt, prompt_furigana, prompt_en, audio_url, explanation, difficulty, is_active) VALUES (30, 'N3', 2, 'multiple_choice', '締め切りが明日なので、今夜は寝る＿＿＿にはいかない。', NULL, NULL, NULL, '〜わけにはいかない expresses moral/circumstantial impossibility ("cannot afford to sleep").', 1, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (89, 30, 'わけ', 1, 0);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (90, 30, 'はず', 0, 1);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (91, 30, 'もの', 0, 2);
INSERT INTO choices (id, question_id, body, is_correct, position) VALUES (92, 30, 'こと', 0, 3);
